@extends('layouts.app')

@section('content')
    <div class="container-fluid px-5">
        <h4 class="w-100 text-center">Buyurtmachilar</h4>
        <table id="usersTable" class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>#</th>
                    <th>FIO</th>
                    <th>Addres</th>
                    <th>Phone</th>
                    <th>Jami buyurtmalar</th>
                    <th>Aktiv</th>
                    <th>Yakunlandi</th>
                    <th>Bekor qilindi</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>1</td>
                    <td>in</td>
                    <td>in</td>
                    <td>ss</td>
                    <td>in</td>
                    <td>6095</td>
                    <td>Moircy</td>
                    <td>2000/11/01</td>
                    <td>33%</td>
                </tr>
                <tr>
                    <td>1</td>
                    <td>in</td>
                    <td>in</td>
                    <td>ss</td>
                    <td>in</td>
                    <td>6095</td>
                    <td>Moircy</td>
                    <td>2000/11/01</td>
                    <td>33%</td>
                </tr>
                <tr>
                    <td>1</td>
                    <td>in</td>
                    <td>in</td>
                    <td>ss</td>
                    <td>in</td>
                    <td>6095</td>
                    <td>Moircy</td>
                    <td>2000/11/01</td>
                    <td>33%</td>
                </tr>
                <tr>
                    <td>1</td>
                    <td>in</td>
                    <td>in</td>
                    <td>ss</td>
                    <td>in</td>
                    <td>6095</td>
                    <td>Moircy</td>
                    <td>2000/11/01</td>
                    <td>33%</td>
                </tr>
                <tr>
                    <td>1</td>
                    <td>in</td>
                    <td>in</td>
                    <td>in</td>
                    <td>ss</td>
                    <td>6095</td>
                    <td>Moircy</td>
                    <td>2000/11/01</td>
                    <td>33%</td>
                </tr>
                <tr>
                    <td>1</td>
                    <td>in</td>
                    <td>in</td>
                    <td>ss</td>
                    <td>in</td>
                    <td>6095</td>
                    <td>Moircy</td>
                    <td>2000/11/01</td>
                    <td>33%</td>
                </tr>
                <tr>
                    <td>1</td>
                    <td>in</td>
                    <td>in</td>
                    <td>ss</td>
                    <td>in</td>
                    <td>6095</td>
                    <td>Moircy</td>
                    <td>2000/11/01</td>
                    <td>33%</td>
                </tr>
                <tr>
                    <td>1</td>
                    <td>in</td>
                    <td>in</td>
                    <td>in</td>
                    <td>ss</td>
                    <td>6095</td>
                    <td>Moircy</td>
                    <td>2000/11/01</td>
                    <td>33%</td>
                </tr>
                <tr>
                    <td>1</td>
                    <td>in</td>
                    <td>in</td>
                    <td>in</td>
                    <td>ss</td>
                    <td>6095</td>
                    <td>Moircy</td>
                    <td>2000/11/01</td>
                    <td>33%</td>
                </tr>
                <tr>
                    <td>1</td>
                    <td>in</td>
                    <td>in</td>
                    <td>ss</td>
                    <td>in</td>
                    <td>6095</td>
                    <td>Moircy</td>
                    <td>2000/11/01</td>
                    <td>33%</td>
                </tr>
                <tr>
                    <td>1</td>
                    <td>in</td>
                    <td>in</td>
                    <td>in</td>
                    <td>6095</td>
                    <td>ss</td>
                    <td>Moircy</td>
                    <td>2000/11/01</td>
                    <td>33%</td>
                </tr>
                <tr>
                    <td>1</td>
                    <td>in</td>
                    <td>ss</td>
                    <td>in</td>
                    <td>in</td>
                    <td>6095</td>
                    <td>Moircy</td>
                    <td>2000/11/01</td>
                    <td>33%</td>
                </tr>
            </tbody>
        </table>
    </div>
@endsection